version: '3'

services:
  app:
    container_name: nestjs-course-app
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    container_name: nestjs-course-db
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestjs-course

  pgadmin:
    container_name: nestjs-course-pgadmin
    image: dpage/pgadmin4
    tty: true
    ports:
      - '8000:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
